import { createClient } from '@supabase/supabase-js';
import { Pool } from 'pg';
import sharp from 'sharp';
import type { WorkerConfig } from './config.js';
import { transcodeVideo } from './video-processor.js';
const bucket='portfolio-private'; type QueueRow={msg_id:number;message:{mediaId?:string}};
export const signatureOk=(b:Buffer,m:string):boolean=>m==='image/jpeg'?(b[0]===255&&b[1]===216&&b[2]===255):m==='image/png'?b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):m==='image/webp'?(b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP'):m==='video/mp4'?b.toString('ascii',4,8)==='ftyp':m==='video/webm'?b.subarray(0,4).equals(Buffer.from([26,69,223,163])):false;
export function startMediaProcessor(c:WorkerConfig):()=>Promise<void>{if(!c.databaseUrl||!c.supabaseUrl||!c.supabaseSecretKey)return async()=>{};const pool=new Pool({connectionString:c.databaseUrl,ssl:{rejectUnauthorized:false}}),sb=createClient(c.supabaseUrl,c.supabaseSecretKey,{auth:{persistSession:false}});let active=true,busy=false;
 const tick=async()=>{if(!active||busy)return;busy=true;let row:QueueRow|undefined;try{row=(await pool.query<QueueRow>("select msg_id,message from pgmq.read('media_processing',60,1)")).rows[0];const id=row?.message.mediaId;if(!id)return;const a=(await pool.query('select * from media_assets where id=$1',[id])).rows[0];if(!a)return;await pool.query("update media_assets set processing_status='PROCESSING',updated_at=now() where id=$1",[id]);const dl=await sb.storage.from(bucket).download(a.object_path);if(dl.error)throw new Error(dl.error.message);const bytes=Buffer.from(await dl.data.arrayBuffer());if(bytes.includes(Buffer.from('EICAR-STANDARD-ANTIVIRUS-TEST-FILE'))){await pool.query("update media_assets set processing_status='QUARANTINED',failure_reason='Malware test signature detected',updated_at=now() where id=$1",[id]);return}if(!signatureOk(bytes,a.mime_type)){await pool.query("update media_assets set processing_status='QUARANTINED',failure_reason='File signature does not match MIME type',updated_at=now() where id=$1",[id]);return}if(a.media_type==='VIDEO'){const out=await transcodeVideo(bytes),processedPath=`processed/${id}.mp4`,thumbnailPath=`thumbnails/${id}.webp`;for(const [path,data,type]of [[processedPath,out.video,'video/mp4'],[thumbnailPath,out.thumbnail,'image/webp']]as const){const up=await sb.storage.from(bucket).upload(path,data,{contentType:type,upsert:true});if(up.error)throw new Error(up.error.message)}await pool.query("update media_assets set processing_status='READY',mime_type='video/mp4',processed_path=$2,thumbnail_path=$3,failure_reason=null,updated_at=now() where id=$1",[id,processedPath,thumbnailPath]);return}const image=sharp(bytes,{failOn:'error'}).rotate(),meta=await image.metadata(),processed=await image.clone().resize({width:1600,height:1600,fit:'inside',withoutEnlargement:true}).webp({quality:82}).toBuffer(),thumb=await image.clone().resize({width:480,height:480,fit:'cover'}).webp({quality:78}).toBuffer(),processedPath=`processed/${id}.webp`,thumbnailPath=`thumbnails/${id}.webp`;for(const [path,data]of [[processedPath,processed],[thumbnailPath,thumb]]as const){const up=await sb.storage.from(bucket).upload(path,data,{contentType:'image/webp',upsert:true});if(up.error)throw new Error(up.error.message)}await pool.query("update media_assets set processing_status='READY',processed_path=$2,thumbnail_path=$3,width=$4,height=$5,failure_reason=null,updated_at=now() where id=$1",[id,processedPath,thumbnailPath,meta.width??null,meta.height??null]);}catch(e){if(row?.message.mediaId)await pool.query("update media_assets set processing_status='FAILED',failure_reason=$2,updated_at=now() where id=$1",[row.message.mediaId,e instanceof Error?e.message:'Processing failed']);}finally{if(row)await pool.query("select pgmq.delete('media_processing',$1)",[row.msg_id]);busy=false}};
 const timer=setInterval(()=>void tick(),3000);void tick();return async()=>{active=false;clearInterval(timer);await pool.end()};}
