import HomeInteractive from './home-interactive';
import Icon, { type IconName } from './ui-icon';

const categories = [
  ['Photography', 'Stories that feel like you', 'photo'], ['Wedding venues', 'Spaces for every celebration', 'venue'],
  ['Bridal makeup', 'Artists for your perfect look', 'makeup'], ['Catering', 'Menus your guests remember', 'catering'],
  ['Decor & planning', 'Thoughtful details, beautifully done', 'decor'], ['Music & entertainment', 'Set the mood for every moment', 'music'],
] as const;
const assurances = [
  ['01', 'Verified professionals', 'Clear business details and trust signals help you choose with confidence.'],
  ['02', 'Transparent discovery', 'Compare services, portfolios and packages without hidden ranking tricks.'],
  ['03', 'Privacy by design', 'Your contact details stay private until you explicitly choose to share them.'],
  ['04', 'Direct connection', 'Speak directly with professionals and agree on the details that matter.'],
] as const;

export default function HomePage() { return <main className="market-home">
  <header className="market-nav"><a className="market-logo" href="/" aria-label="WedConnect home"><span>Wed</span>Connect</a><nav aria-label="Primary navigation"><a href="/coimbatore/photography">Find vendors</a><a href="#categories">Categories</a><a href="#how-it-works">How it works</a><a href="/shortlists">Shortlists</a></nav><div className="market-actions"><a className="login-link" href="/sign-in">Sign in</a><a className="nav-cta" href="/sign-in?role=VENDOR_OWNER">List your business</a></div></header>
  <section className="market-hero" aria-labelledby="home-title"><div className="hero-copy"><p className="market-kicker">Wedding planning, made wonderfully simple</p><h1 id="home-title">Find wedding professionals you’ll <em>love</em></h1><p className="market-lede">Discover trusted local experts, explore their work and request quotes—all while staying in control of your privacy.</p><form className="vendor-search" action="/coimbatore/photography"><label><span>City</span><select name="city" defaultValue="coimbatore"><option value="coimbatore">Coimbatore</option><option value="chennai">Chennai</option><option value="madurai">Madurai</option></select></label><label><span>Looking for</span><select name="category" defaultValue="photography"><option value="photography">Photography</option><option value="venues">Wedding venues</option><option value="makeup">Bridal makeup</option><option value="catering">Catering</option></select></label><button type="submit">Search vendors <span aria-hidden="true">→</span></button></form><div className="hero-promises"><span>✓ Free to explore</span><span>✓ Privacy-first enquiries</span><span>✓ Verified profiles</span></div></div><div className="hero-visual" aria-label="A joyful wedding celebration"><div className="hero-photo"><span className="photo-flower flower-one"/><span className="photo-flower flower-two"/><div className="couple-mark">W<span>♥</span>C</div></div><div className="floating-card"><span className="float-icon">✓</span><div><strong>Trusted professionals</strong><small>Thoughtfully reviewed profiles</small></div></div><div className="floating-rating"><strong>4.9</strong><span>★★★★★</span><small>community experience</small></div></div></section>
  <section className="category-section" id="categories"><div className="section-heading"><div><p className="market-kicker">Browse by category</p><h2>Everything your day needs</h2><p>Start with a service and meet professionals who understand your celebration.</p></div><a href="/coimbatore/photography">View all categories →</a></div><div className="category-grid">{categories.map(([name, description, theme]) => {const icon:IconName=theme==='photo'?'camera':theme==='venue'?'venue':theme==='makeup'?'sparkles':theme==='catering'?'food':theme==='decor'?'flower':'music';return <a className={`category-card category-${theme}`} href="/coimbatore/photography" key={name}><div className="category-art"><span><Icon name={icon}/></span></div><div><h3>{name}</h3><p>{description}</p><span className="explore">Explore <Icon name="arrow"/></span></div></a>})}</div></section>
  <section className="trust-strip" aria-label="Platform benefits"><div><Icon name="shield"/><span><strong>Verified</strong><small>business profiles</small></span></div><div><Icon name="lock"/><span><strong>Private</strong><small>contact sharing</small></span></div><div><Icon name="message"/><span><strong>Direct</strong><small>vendor enquiries</small></span></div><div><Icon name="pin"/><span><strong>Local</strong><small>city-first discovery</small></span></div></section>
  <HomeInteractive />
  <section className="why-section"><div className="why-intro"><p className="market-kicker">Why couples choose WedConnect</p><h2>More clarity. Less wedding-planning noise.</h2><p>Move from inspiration to a confident shortlist with transparent information, useful trust signals and respectful contact controls.</p><a className="coral-button" href="/requirements/new">Tell us what you need →</a></div><div className="assurance-grid">{assurances.map(([number,title,text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="process-section" id="how-it-works"><div className="section-heading centered"><div><p className="market-kicker">A simple process</p><h2>From search to shortlist in three steps</h2><p>No pressure, no complicated setup—just a clear path to professionals who fit.</p></div></div><div className="process-grid"><article><span>01</span><div className="process-icon"><Icon name="search"/></div><h3>Discover</h3><p>Search by city and service, then refine by budget, style and availability.</p></article><article><span>02</span><div className="process-icon"><Icon name="heart"/></div><h3>Compare</h3><p>Review portfolios, packages and trust signals. Save the ones you love.</p></article><article><span>03</span><div className="process-icon"><Icon name="send"/></div><h3>Connect</h3><p>Send a private requirement and choose when to reveal your contact details.</p></article></div></section>
  <section className="home-cta"><div><p className="market-kicker">Ready when you are</p><h2>Your perfect wedding team is closer than you think.</h2></div><div><a className="light-button" href="/coimbatore/photography">Find vendors</a><a className="outline-light" href="/vendor/onboarding">Join as a vendor</a></div></section>
  <footer className="market-footer"><div className="footer-brand"><a className="market-logo" href="/"><span>Wed</span>Connect</a><p>A trusted, privacy-first place to discover independent wedding professionals across India.</p></div><div><h3>Plan</h3><a href="/coimbatore/photography">Find vendors</a><a href="/shortlists">Shortlists</a><a href="/requirements/new">Create requirement</a></div><div><h3>For vendors</h3><a href="/vendor/onboarding">List your business</a><a href="/vendor/leads">Manage leads</a><a href="/vendor/billing">Plans & billing</a></div><div><h3>Trust</h3><a href="/vendor/trust-center">Trust centre</a><a href="/support/grievance">Grievance support</a><a href="#how-it-works">How it works</a></div><p className="footer-legal">© 2026 WedConnect · Customers and vendors contract directly with each other.</p></footer>
</main> }
