import{ConflictException,ForbiddenException,Inject,Injectable,NotFoundException}from'@nestjs/common';import{randomUUID}from'node:crypto';import{createClient,type SupabaseClient}from'@supabase/supabase-js';import{PrismaService}from'../platform/prisma.service';import{appealDecisionInput,appealInput,caseInput,evidenceInput,grievanceInput,reportInput,trustResolutionInput,verificationDecisionInput}from'./trust.schemas';
const BUCKET='verification-evidence';const DISCLAIMER='Information submitted to WedConnect was checked for this scope. This does not guarantee service quality, availability, safety or future conduct.';
@Injectable()export class TrustService{private readonly storage:SupabaseClient;constructor(@Inject(PrismaService)private readonly db:PrismaService){const u=process.env.SUPABASE_URL,k=process.env.SUPABASE_SECRET_KEY;if(!u||!k)throw new Error('Supabase server credentials are required');this.storage=createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}})}
 private async member(userId:string,businessId:string){if(!await this.db.vendorMember.findFirst({where:{userId,businessId,active:true}}))throw new ForbiddenException('Active vendor membership required')}
 private audit(actorUserId:string|null,action:string,subjectType:string,subjectId:string,metadata:object={}){return this.db.trustAuditLog.create({data:{actorUserId,action,subjectType,subjectId,metadata}})}
 async createCase(userId:string,businessId:string,body:unknown){await this.member(userId,businessId);const d=caseInput.parse(body),existing=await this.db.verificationCase.findFirst({where:{businessId,scope:d.scope,status:{in:['DRAFT','SUBMITTED','ASSIGNED','CLARIFICATION_REQUIRED']}}});if(existing)throw new ConflictException('An active case already exists for this scope');const c=await this.db.verificationCase.create({data:{businessId,submittedByUserId:userId,scope:d.scope}});await this.audit(userId,'verification.case.created','verification_case',c.id,{scope:d.scope});return c}
 async myCases(userId:string,businessId:string){await this.member(userId,businessId);return this.db.verificationCase.findMany({where:{businessId},orderBy:{createdAt:'desc'},include:{evidence:{select:{id:true,label:true,mimeType:true,byteSize:true,status:true,createdAt:true}},badges:true}})}
 async evidenceUpload(userId:string,businessId:string,caseId:string,body:unknown){await this.member(userId,businessId);const d=evidenceInput.parse(body),c=await this.db.verificationCase.findFirst({where:{id:caseId,businessId,status:{in:['DRAFT','CLARIFICATION_REQUIRED']}}});if(!c)throw new NotFoundException('Editable verification case not found');const ext=d.filename.split('.').pop()?.toLowerCase()??'bin',path=`${businessId}/${caseId}/${randomUUID()}.${ext}`,e=await this.db.verificationEvidence.create({data:{caseId,uploadedByUserId:userId,label:d.label,objectPath:path,mimeType:d.mimeType,byteSize:d.byteSize,expiresAt:new Date(Date.now()+365*86400000)}}),{data,error}=await this.storage.storage.from(BUCKET).createSignedUploadUrl(path);if(error){await this.db.verificationEvidence.delete({where:{id:e.id}});throw new ConflictException('Private evidence upload could not be signed')}await this.audit(userId,'verification.evidence.intent','verification_evidence',e.id,{caseId,mimeType:d.mimeType});return{evidenceId:e.id,signedUrl:data.signedUrl,token:data.token,expiresInSeconds:600}}
 async submit(userId:string,businessId:string,caseId:string){await this.member(userId,businessId);const c=await this.db.verificationCase.findFirst({where:{id:caseId,businessId,status:{in:['DRAFT','CLARIFICATION_REQUIRED']},evidence:{some:{}}}});if(!c)throw new ConflictException('Add evidence before submitting');const x=await this.db.verificationCase.update({where:{id:caseId},data:{status:'SUBMITTED',submittedAt:new Date()}});await this.audit(userId,'verification.case.submitted','verification_case',caseId);return x}
 assigned(userId:string){return this.db.verificationCase.findMany({where:{assignedToUserId:userId,status:{in:['ASSIGNED','CLARIFICATION_REQUIRED']}},orderBy:{updatedAt:'asc'},include:{business:{select:{id:true,name:true}},evidence:{select:{id:true,label:true,mimeType:true,byteSize:true,status:true,createdAt:true}}}})}
 async assign(actorUserId:string,caseId:string,verifierUserId:string){const c=await this.db.verificationCase.findFirst({where:{id:caseId,status:'SUBMITTED'}});if(!c)throw new NotFoundException('Submitted case not found');const x=await this.db.verificationCase.update({where:{id:caseId},data:{assignedToUserId:verifierUserId,status:'ASSIGNED'}});await this.audit(actorUserId,'verification.case.assigned','verification_case',caseId,{verifierUserId});return x}
 async viewEvidence(userId:string,evidenceId:string,purpose:string){const e=await this.db.verificationEvidence.findFirst({where:{id:evidenceId,verificationCase:{assignedToUserId:userId,status:{in:['ASSIGNED','CLARIFICATION_REQUIRED']}}}});if(!e)throw new ForbiddenException('Evidence is not assigned to this verifier');const{data,error}=await this.storage.storage.from(BUCKET).createSignedUrl(e.objectPath,300);if(error)throw new NotFoundException('Evidence unavailable');await this.db.$transaction([this.db.evidenceAccessLog.create({data:{evidenceId,viewerUserId:userId,purpose}}),this.db.trustAuditLog.create({data:{actorUserId:userId,action:'verification.evidence.viewed',subjectType:'verification_evidence',subjectId:evidenceId,metadata:{purpose}}})]);return{signedUrl:data.signedUrl,expiresInSeconds:300,mimeType:e.mimeType}}
 async decide(userId:string,caseId:string,body:unknown){const d=verificationDecisionInput.parse(body),c=await this.db.verificationCase.findFirst({where:{id:caseId,assignedToUserId:userId,status:{in:['ASSIGNED','CLARIFICATION_REQUIRED']}}});if(!c)throw new ForbiddenException('Assigned active case required');return this.db.$transaction(async tx=>{const x=await tx.verificationCase.update({where:{id:caseId},data:{status:d.decision,decisionReason:d.reason,internalNotes:d.internalNotes??null,decidedAt:d.decision==='CLARIFICATION_REQUIRED'?null:new Date()}});if(d.decision==='APPROVED')await tx.verificationBadge.create({data:{businessId:c.businessId,caseId,scope:c.scope,checkedAt:new Date(),expiresAt:d.expiresAt??null,disclaimer:DISCLAIMER}});await tx.trustAuditLog.create({data:{actorUserId:userId,action:`verification.case.${d.decision.toLowerCase()}`,subjectType:'verification_case',subjectId:caseId,metadata:{reason:d.reason}}});return x})}
 async badges(slug:string){return this.db.verificationBadge.findMany({where:{business:{slug,status:'APPROVED',publicVisible:true},revokedAt:null,OR:[{expiresAt:null},{expiresAt:{gt:new Date()}}]},select:{scope:true,checkedAt:true,expiresAt:true,disclaimer:true}})}
 async report(userId:string,body:unknown){const d=reportInput.parse(body),x=await this.db.trustReport.create({data:{reporterUserId:userId,businessId:d.businessId??null,type:d.type,subjectType:d.subjectType,subjectId:d.subjectId??null,description:d.description}});await this.audit(userId,'trust.report.created','trust_report',x.id,{type:d.type});return x}
 async grievance(userId:string,body:unknown){const d=grievanceInput.parse(body),x=await this.db.grievance.create({data:{submitterUserId:userId,...d}});await this.audit(userId,'grievance.created','grievance',x.id,{type:d.type});return x}
 async mine(userId:string){return{grievances:await this.db.grievance.findMany({where:{submitterUserId:userId},orderBy:{createdAt:'desc'}}),appeals:await this.db.appeal.findMany({where:{appellantUserId:userId},orderBy:{createdAt:'desc'}})}}
 async appeal(userId:string,body:unknown){const d=appealInput.parse(body),x=await this.db.appeal.create({data:{appellantUserId:userId,grievanceId:d.grievanceId??null,targetType:d.targetType,targetId:d.targetId,grounds:d.grounds}});await this.audit(userId,'appeal.created','appeal',x.id,{targetType:d.targetType,targetId:d.targetId});return x}
 queues(){return Promise.all([this.db.trustReport.findMany({where:{status:{in:['OPEN','REVIEWING']}},orderBy:{createdAt:'asc'}}),this.db.grievance.findMany({where:{status:{in:['OPEN','REVIEWING']}},orderBy:{createdAt:'asc'}}),this.db.appeal.findMany({where:{status:{in:['OPEN','REVIEWING']}},orderBy:{createdAt:'asc'}})]).then(([reports,grievances,appeals])=>({reports,grievances,appeals}))}
 async resolve(actorUserId:string,type:'report'|'grievance',id:string,body:unknown){const d=trustResolutionInput.parse(body),model=type==='report'?this.db.trustReport:this.db.grievance;const result=await (model as typeof this.db.trustReport).update({where:{id},data:{status:d.status,resolution:d.resolution}});await this.audit(actorUserId,`${type}.resolved`,type,id,{status:d.status});return result}
 async decideAppeal(actorUserId:string,id:string,body:unknown){const d=appealDecisionInput.parse(body),x=await this.db.appeal.update({where:{id},data:{status:d.decision,decision:d.reason,decidedByUserId:actorUserId,decidedAt:new Date()}});await this.audit(actorUserId,'appeal.decided','appeal',id,{decision:d.decision});return x}
 audits(subjectType:string,subjectId:string){return this.db.trustAuditLog.findMany({where:{subjectType,subjectId},orderBy:{createdAt:'desc'}})} }
