/* eslint-disable @typescript-eslint/no-explicit-any -- Razorpay event entities vary by signed webhook type. */
import{ConflictException,ForbiddenException,Inject,Injectable,ServiceUnavailableException,UnauthorizedException}from'@nestjs/common';import{createHash,createHmac,timingSafeEqual}from'node:crypto';import{PrismaService}from'../platform/prisma.service';import{campaignInput,orderInput}from'./billing.schemas';
@Injectable()export class BillingService{
 constructor(@Inject(PrismaService)private readonly db:PrismaService){}
 private async member(u:string,b:string){if(!await this.db.vendorMember.findFirst({where:{userId:u,businessId:b,active:true}}))throw new ForbiddenException('Active vendor membership required')}
 catalog(){return Promise.all([this.db.subscriptionPlan.findMany({where:{active:true},orderBy:{sortOrder:'asc'}}),this.db.creditPack.findMany({where:{active:true},orderBy:{sortOrder:'asc'}})]).then(([plans,creditPacks])=>({plans,creditPacks,checkoutConfigured:!!process.env.RAZORPAY_KEY_ID}))}
 async createOrder(u:string,b:string,body:unknown){await this.member(u,b);const keyId=process.env.RAZORPAY_KEY_ID,secret=process.env.RAZORPAY_KEY_SECRET;if(!keyId||!secret)throw new ServiceUnavailableException('Razorpay checkout is not configured');const d=orderInput.parse(body),prior=await this.db.billingOrder.findUnique({where:{idempotencyKey:d.idempotencyKey}});if(prior){if(prior.businessId!==b)throw new ForbiddenException();return prior}let amount=0,subscriptionId:null|string=null,creditPackId:null|string=null;if(d.type==='SUBSCRIPTION'){const p=await this.db.subscriptionPlan.findFirstOrThrow({where:{id:d.planId as string,active:true}});amount=d.interval==='YEARLY'?p.yearlyPricePaise:p.monthlyPricePaise;subscriptionId=(await this.db.vendorSubscription.create({data:{businessId:b,planId:p.id,interval:d.interval!}})).id}else{const p=await this.db.creditPack.findFirstOrThrow({where:{id:d.creditPackId as string,active:true}});amount=p.pricePaise;creditPackId=p.id}const local=await this.db.billingOrder.create({data:{businessId:b,type:d.type,amountPaise:amount,idempotencyKey:d.idempotencyKey,subscriptionId,creditPackId}}),receipt=`wc_${local.id.replaceAll('-','').slice(0,32)}`,res=await fetch('https://api.razorpay.com/v1/orders',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${keyId}:${secret}`).toString('base64')}`,'Content-Type':'application/json'},body:JSON.stringify({amount,currency:'INR',receipt,notes:{wedconnect_order_id:local.id,business_id:b}})});if(!res.ok)throw new ServiceUnavailableException('Payment order creation failed');const remote=await res.json()as{id:string};return this.db.billingOrder.update({where:{id:local.id},data:{razorpayOrderId:remote.id}})}
 async mine(u:string,b:string){await this.member(u,b);return{orders:await this.db.billingOrder.findMany({where:{businessId:b},orderBy:{createdAt:'desc'},include:{invoice:true}}),subscriptions:await this.db.vendorSubscription.findMany({where:{businessId:b},orderBy:{createdAt:'desc'},include:{plan:true}}),credits:await this.db.vendorCreditAccount.findUnique({where:{businessId:b},include:{ledger:{orderBy:{createdAt:'desc'},take:100}}})}}
 async campaign(u:string,b:string,body:unknown){await this.member(u,b);const d=campaignInput.parse(body);return this.db.promotionCampaign.create({data:{businessId:b,cityId:d.cityId,localityId:d.localityId??null,categoryId:d.categoryId,startsAt:d.startsAt,endsAt:d.endsAt,impressionLimit:d.impressionLimit,clickLimit:d.clickLimit,frequencyCap:d.frequencyCap,status:'DRAFT',disclosure:'Sponsored'}})}
 private valid(raw:Buffer,sig:string,secret:string){const expected=createHmac('sha256',secret).update(raw).digest(),got=Buffer.from(sig,'hex');return got.length===expected.length&&timingSafeEqual(got,expected)}
 async webhook(raw:Buffer,signature:string,eventId:string){const secret=process.env.RAZORPAY_WEBHOOK_SECRET;if(!secret||!eventId||!this.valid(raw,signature,secret))throw new UnauthorizedException('Invalid webhook signature');const hash=createHash('sha256').update(raw).digest('hex'),payload=JSON.parse(raw.toString('utf8'))as any;if(await this.db.paymentWebhookEvent.findUnique({where:{providerEventId:eventId}}))return{duplicate:true};await this.db.paymentWebhookEvent.create({data:{providerEventId:eventId,eventType:String(payload.event),payloadHash:hash}});if(!['payment.captured','order.paid'].includes(payload.event)){await this.db.paymentWebhookEvent.update({where:{providerEventId:eventId},data:{processedAt:new Date()}});return{accepted:true}}const payment=payload.payload?.payment?.entity,orderId=payment?.order_id??payload.payload?.order?.entity?.id;if(!orderId)throw new ConflictException('Webhook order is missing');await this.fulfil(orderId,payment?.id,eventId,payment?.status);return{accepted:true}}
 private async fulfil(orderId:string,paymentId:string|undefined,eventId:string,paymentStatus:string|undefined){await this.db.$transaction(async tx=>{const o=await tx.billingOrder.findUnique({where:{razorpayOrderId:orderId},include:{creditPack:true,subscription:true}});if(!o||o.status==='PAID')return;if(paymentStatus&&paymentStatus!=='captured')throw new ConflictException('Payment is not captured');await tx.billingOrder.update({where:{id:o.id},data:{status:'PAID',razorpayPaymentId:paymentId??null,paidAt:new Date()}});if(o.creditPack){const a=await tx.vendorCreditAccount.upsert({where:{businessId:o.businessId},create:{businessId:o.businessId,balance:o.creditPack.credits},update:{balance:{increment:o.creditPack.credits}}});await tx.vendorCreditLedger.create({data:{businessId:o.businessId,amount:o.creditPack.credits,balanceAfter:a.balance,reason:'CREDIT_PACK_PURCHASE',reference:o.id}})}if(o.subscription)await tx.vendorSubscription.update({where:{id:o.subscription.id},data:{status:'ACTIVE',startsAt:new Date(),endsAt:new Date(Date.now()+(o.subscription.interval==='YEARLY'?365:30)*86400000)}});await tx.invoice.create({data:{businessId:o.businessId,orderId:o.id,number:`WC-${new Date().getUTCFullYear()}-${o.id.slice(0,8).toUpperCase()}`,amountPaise:o.amountPaise}});await tx.paymentWebhookEvent.update({where:{providerEventId:eventId},data:{processedAt:new Date()}})})}
}
