import { ConflictException,ForbiddenException,Inject,Injectable,NotFoundException } from '@nestjs/common';
import { createHash,randomBytes } from 'node:crypto';
import { PrismaService } from '../platform/prisma.service';
import { addItemInput,compareInput,createReviewInput,createShareInput,createShortlistInput,moderateReviewInput,replyInput } from './shortlist.schemas';

@Injectable()
export class ShortlistsService{
 constructor(@Inject(PrismaService)private readonly db:PrismaService){}
 private hash(token:string){return createHash('sha256').update(token).digest('hex')}
 private async owned(userId:string,id:string){const list=await this.db.customerShortlist.findFirst({where:{id,customerId:userId}});if(!list)throw new NotFoundException('Shortlist not found');return list}
 private vendorSelect(){return {id:true,name:true,slug:true,description:true,yearsExperience:true,outstationAvailable:true,baseCity:{select:{name:true,slug:true}},categories:{select:{isPrimary:true,category:{select:{name:true,slug:true}}}},services:{where:{active:true},select:{name:true,pricingType:true,price:true}},packages:{where:{active:true},select:{name:true,price:true,inclusions:true}},reviews:{where:{status:'APPROVED' as const},select:{rating:true}}}}
 async create(userId:string,body:unknown){const d=createShortlistInput.parse(body);return this.db.customerShortlist.create({data:{customerId:userId,name:d.name,eventLabel:d.eventLabel??null,cityLabel:d.cityLabel??null}})}
 async mine(userId:string){return this.db.customerShortlist.findMany({where:{customerId:userId},orderBy:{updatedAt:'desc'},include:{items:{orderBy:{createdAt:'desc'},include:{business:{select:this.vendorSelect()}}},shares:{where:{revokedAt:null},select:{id:true,expiresAt:true,createdAt:true}}}})}
 async add(userId:string,id:string,body:unknown){await this.owned(userId,id);const d=addItemInput.parse(body),vendor=await this.db.vendorBusiness.findFirst({where:{id:d.businessId,status:'APPROVED',publicVisible:true}});if(!vendor)throw new NotFoundException('Public vendor not found');return this.db.customerShortlistItem.upsert({where:{shortlistId_businessId:{shortlistId:id,businessId:d.businessId}},create:{shortlistId:id,businessId:d.businessId,note:d.note??null},update:{note:d.note??null}})}
 async remove(userId:string,id:string,businessId:string){await this.owned(userId,id);await this.db.customerShortlistItem.deleteMany({where:{shortlistId:id,businessId}});return{removed:true}}
 async compare(userId:string,id:string,body:unknown){await this.owned(userId,id);const d=compareInput.parse(body),count=await this.db.customerShortlistItem.count({where:{shortlistId:id,businessId:{in:d.businessIds}}});if(count!==d.businessIds.length)throw new ForbiddenException('Every compared vendor must be in this shortlist');return this.comparison(d.businessIds)}
 private async comparison(ids:string[]){const vendors=await this.db.vendorBusiness.findMany({where:{id:{in:ids},status:'APPROVED',publicVisible:true},select:this.vendorSelect()});return vendors.map(v=>{const ratings=v.reviews.map(r=>r.rating);return{...v,reviews:undefined,ratingCount:ratings.length,averageRating:ratings.length?Number((ratings.reduce((a,b)=>a+b,0)/ratings.length).toFixed(1)):null}})}
 async share(userId:string,id:string,body:unknown){await this.owned(userId,id);const d=createShareInput.parse(body),token=randomBytes(24).toString('base64url'),expiresAt=new Date(Date.now()+d.expiresInDays*86400000);await this.db.shortlistShare.create({data:{shortlistId:id,tokenHash:this.hash(token),expiresAt}});return{token,path:`/shortlists/shared/${token}`,expiresAt}}
 async revoke(userId:string,id:string,shareId:string){await this.owned(userId,id);const done=await this.db.shortlistShare.updateMany({where:{id:shareId,shortlistId:id,revokedAt:null},data:{revokedAt:new Date()}});if(!done.count)throw new NotFoundException('Active share not found');return{revoked:true}}
 async publicShare(token:string){const share=await this.db.shortlistShare.findUnique({where:{tokenHash:this.hash(token)},include:{shortlist:{include:{items:{include:{business:{select:this.vendorSelect()}}}}}}});if(!share||share.revokedAt||(share.expiresAt&&share.expiresAt<=new Date()))throw new NotFoundException('Shared shortlist is unavailable');return{id:share.shortlist.id,name:share.shortlist.name,eventLabel:share.shortlist.eventLabel,cityLabel:share.shortlist.cityLabel,vendors:share.shortlist.items.map(x=>({...x.business,note:x.note})),expiresAt:share.expiresAt}}
 async createReview(userId:string,businessId:string,body:unknown){const d=createReviewInput.parse(body),lead=await this.db.leadRecipient.findFirst({where:{id:d.leadRecipientId,businessId,requirement:{customerId:userId},status:{in:['RESPONDED','CONTACT_SHARED','IN_DISCUSSION','CLOSED']}}});if(!lead)throw new ForbiddenException('A verified vendor interaction is required to review');try{return await this.db.vendorReview.create({data:{customerId:userId,businessId,leadRecipientId:d.leadRecipientId,rating:d.rating,title:d.title,body:d.body,eventDate:d.eventDate??null,status:'PENDING'}})}catch{throw new ConflictException('This interaction has already been reviewed')}}
 async publicReviews(slug:string){return this.db.vendorReview.findMany({where:{business:{slug,status:'APPROVED',publicVisible:true},status:'APPROVED'},orderBy:{publishedAt:'desc'},select:{id:true,rating:true,title:true,body:true,eventDate:true,vendorReply:true,vendorRepliedAt:true,publishedAt:true,customer:{select:{displayName:true}}}})}
 private async member(userId:string,businessId:string){if(!await this.db.vendorMember.findFirst({where:{userId,businessId,active:true}}))throw new ForbiddenException('Active vendor membership required')}
 async reply(userId:string,businessId:string,reviewId:string,body:unknown){await this.member(userId,businessId);const d=replyInput.parse(body),review=await this.db.vendorReview.findFirst({where:{id:reviewId,businessId,status:'APPROVED'}});if(!review)throw new NotFoundException('Published review not found');return this.db.vendorReview.update({where:{id:reviewId},data:{vendorReply:d.reply,vendorRepliedAt:new Date()}})}
 async queue(){return this.db.vendorReview.findMany({where:{status:'PENDING'},orderBy:{createdAt:'asc'},include:{business:{select:{id:true,name:true}},customer:{select:{id:true,displayName:true}}}})}
 async moderate(actorUserId:string,id:string,body:unknown){const d=moderateReviewInput.parse(body),review=await this.db.vendorReview.findUnique({where:{id}});if(!review)throw new NotFoundException('Review not found');return this.db.$transaction(async tx=>{const updated=await tx.vendorReview.update({where:{id},data:{status:d.decision,publishedAt:d.decision==='APPROVED'?new Date():null}});await tx.reviewModerationEvent.create({data:{reviewId:id,actorUserId,fromStatus:review.status,toStatus:d.decision,reason:d.reason??null}});return updated})}
}
