import type { Metadata } from 'next';
type Result={id:string;name:string;slug:string;description:string|null;rating:number;reviewCount:number;verified:boolean;startingPrice:number|null;languages:string[];score:number;label?:string};
type SearchResponse={sponsored:Result[];organic:Result[];meta:{total:number}};
const api=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000/api/v1';
const categoryImages:Record<string,string>={photography:'/images/home/photography.webp',venues:'/images/home/venue.webp',venue:'/images/home/venue.webp',makeup:'/images/home/makeup.webp',catering:'/images/home/catering.webp',decor:'/images/home/decor.webp',music:'/images/home/music.webp'};
const suggestions=[['Wedding venues','venues','/images/home/venue.webp'],['Bridal makeup','makeup','/images/home/makeup.webp'],['Catering','catering','/images/home/catering.webp']] as const;
const clean=(value:string)=>value.replaceAll('-',' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());
export async function generateMetadata({params}:{params:Promise<{city:string;category:string}>}):Promise<Metadata>{const{city,category}=await params;return{title:`${clean(category)} in ${clean(city)} | WedConnect`,description:`Discover approved ${clean(category)} professionals serving ${clean(city)}.`,alternates:{canonical:`/${city}/${category}`}}}

export default async function DiscoveryPage({params,searchParams}:{params:Promise<{city:string;category:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){const{city,category}=await params,filters=await searchParams,query=new URLSearchParams({city,category});for(const[k,v]of Object.entries(filters))if(typeof v==='string'&&v&&!['city','category'].includes(k))query.set(k,v);let data:SearchResponse={sponsored:[],organic:[],meta:{total:0}},apiAvailable=true;try{const response=await fetch(`${api}/discovery/search?${query}`,{cache:'no-store'});if(response.ok)data=await response.json()as SearchResponse;else apiAvailable=false}catch{apiAvailable=false}const all=[...data.sponsored,...data.organic];return <main className="discover-v2">
  <header className="discover-nav"><a className="market-logo" href="/"><span>Wed</span>Connect</a><nav><a href="/">Home</a><a className="active" href={`/${city}/${category}`}>Find vendors</a><a href="/shortlists">Shortlists</a></nav><div><a href="/sign-in">Sign in</a><a className="nav-cta" href="/sign-in?role=VENDOR_OWNER">List your business</a></div></header>
  <section className="discover-heading"><div className="breadcrumbs"><a href="/">Home</a><span>›</span><a href={`/${city}/${category}`}>{clean(city)}</a><span>›</span><strong>{clean(category)}</strong></div><div className="heading-row"><div><p className="market-kicker">Handpicked for your celebration</p><h1>{clean(category)} in <em>{clean(city)}</em></h1><p>{data.meta.total?`${data.meta.total} approved professionals ready to help`:'Explore trusted local professionals and request a personalised quote.'}</p></div><div className="heading-art"><img src={categoryImages[category]??'/images/home/photography.webp'} alt=""/></div></div>
  <form className="discover-search"><label><span>⌕</span><input name="q" placeholder={`Search ${clean(category).toLowerCase()}`} defaultValue={typeof filters.q==='string'?filters.q:''}/></label><label><small>Location</small><select name="city" defaultValue={city}><option value="coimbatore">Coimbatore</option><option value="chennai">Chennai</option><option value="madurai">Madurai</option></select></label><label><small>Category</small><select name="category" defaultValue={category}><option value="photography">Photography</option><option value="venues">Wedding venues</option><option value="makeup">Bridal makeup</option><option value="catering">Catering</option></select></label><button type="submit">Search</button></form></section>
  <section className="discover-body"><aside className="filter-panel"><div><h2>Filters</h2><a href={`/${city}/${category}`}>Clear all</a></div><fieldset><legend>Budget range</legend><label>Maximum starting price<input name="maxPrice" form="filters" type="number" placeholder="₹ 1,00,000" defaultValue={typeof filters.maxPrice==='string'?filters.maxPrice:''}/></label></fieldset><fieldset><legend>Trust & quality</legend><label className="check-row"><input type="checkbox"/> Verified professionals</label><label className="check-row"><input type="checkbox"/> Rated 4.5 and above</label><label className="check-row"><input type="checkbox"/> Portfolio available</label></fieldset><fieldset><legend>Availability</legend><label className="check-row"><input type="checkbox"/> Available for outstation</label><label className="check-row"><input type="checkbox"/> Responds quickly</label></fieldset><form id="filters"><input type="hidden" name="q" value={typeof filters.q==='string'?filters.q:''}/><button type="submit">Apply filters</button></form><div className="filter-help"><span>◇</span><strong>Need recommendations?</strong><p>Share your requirement and let suitable professionals respond.</p><a href="/requirements/new">Create requirement →</a></div></aside>
  <div className="results-area"><div className="results-toolbar"><div><strong>{data.meta.total} professionals</strong><span> in {clean(city)}</span></div><label>Sort by<select name="sort" defaultValue={typeof filters.sort==='string'?filters.sort:'relevance'}><option value="relevance">Recommended</option><option value="rating">Highest rated</option><option value="price">Lowest price</option><option value="recent">Recently active</option></select></label></div>{!apiAvailable?<EmptyState city={city} category={category} serviceDown/>:all.length?<div className="vendor-grid-v2">{all.map((vendor,index)=><VendorCard vendor={vendor} city={city} category={category} sponsored={data.sponsored.some(item=>item.id===vendor.id)} imageIndex={index}/>)}</div>:<EmptyState city={city} category={category}/>}</div></section>
  <section className="discover-more"><div><p className="market-kicker">Keep exploring</p><h2>Other services for your celebration</h2></div><div>{suggestions.map(([name,slug,image])=><a href={`/${city}/${slug}`} key={slug}><img src={image} alt=""/><span>{name}<b>→</b></span></a>)}</div></section>
</main>}

function VendorCard({vendor,city,category,sponsored,imageIndex}:{vendor:Result;city:string;category:string;sponsored:boolean;imageIndex:number}){const images=[categoryImages[category]??'/images/home/photography.webp','/images/home/hero-couple.webp'];return <article className="vendor-card-v2"><a className="vendor-image" href={`/${city}/${category}/${vendor.slug}`}><img src={images[imageIndex%images.length]} alt={`${vendor.name} portfolio`}/>{sponsored&&<span className="paid-label">Sponsored</span>}<button type="button" aria-label={`Save ${vendor.name}`}>♡</button>{vendor.verified&&<span className="verified-label">✓ Verified</span>}</a><div className="vendor-copy"><div className="vendor-title"><h2><a href={`/${city}/${category}/${vendor.slug}`}>{vendor.name}</a></h2><span>★ {vendor.rating.toFixed(1)} <small>({vendor.reviewCount})</small></span></div><p>{vendor.description??`Professional ${clean(category).toLowerCase()} services in ${clean(city)}.`}</p><div className="vendor-tags"><span>{vendor.languages[0]??'Local expert'}</span><span>Custom packages</span></div><footer><div><small>Starting from</small><strong>{vendor.startingPrice!=null?`₹${vendor.startingPrice.toLocaleString('en-IN')}`:'Custom quote'}</strong></div><a href={`/${city}/${category}/${vendor.slug}`}>View profile →</a></footer></div></article>}
function EmptyState({city,category,serviceDown=false}:{city:string;category:string;serviceDown?:boolean}){return <section className="results-empty"><div className="empty-photo"><img src={categoryImages[category]??'/images/home/photography.webp'} alt=""/></div><div><span>{serviceDown?'Temporarily unavailable':'New professionals joining soon'}</span><h2>{serviceDown?'We couldn’t load the marketplace':'Be first to discover new talent'}</h2><p>{serviceDown?'The API is not responding right now. Refresh in a moment or create a requirement while we reconnect.':`No approved ${clean(category).toLowerCase()} profiles match these filters in ${clean(city)} yet. Create a requirement and we’ll notify you when suitable professionals are available.`}</p><div><a className="dash-primary" href="/requirements/new">Create requirement</a><a href={`/${city}/${category}`}>Reset filters</a></div></div></section>}
