CREATE TYPE "VerificationScope" AS ENUM ('IDENTITY','BUSINESS','ADDRESS','PORTFOLIO');
CREATE TYPE "VerificationCaseStatus" AS ENUM ('DRAFT','SUBMITTED','ASSIGNED','CLARIFICATION_REQUIRED','APPROVED','REJECTED','EXPIRED');
CREATE TYPE "EvidenceStatus" AS ENUM ('PENDING','CLEAN','QUARANTINED','REJECTED');
CREATE TYPE "TrustReportType" AS ENUM ('COPYRIGHT','IMPERSONATION','PRIVACY','FAKE_PORTFOLIO','FRAUD','REVIEW_DISPUTE','OTHER');
CREATE TYPE "TrustCaseStatus" AS ENUM ('OPEN','REVIEWING','ACTIONED','DISMISSED','CLOSED');
CREATE TYPE "GrievanceType" AS ENUM ('PRIVACY','VERIFICATION','MODERATION','SERVICE','OTHER');
CREATE TYPE "AppealStatus" AS ENUM ('OPEN','REVIEWING','UPHELD','OVERTURNED','CLOSED');

CREATE TABLE "verification_cases"("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"business_id" uuid NOT NULL REFERENCES "vendor_businesses"("id") ON DELETE CASCADE,"scope" "VerificationScope" NOT NULL,"status" "VerificationCaseStatus" NOT NULL DEFAULT 'DRAFT',"submitted_by_user_id" uuid NOT NULL REFERENCES "app_users"("id") ON DELETE RESTRICT,"assigned_to_user_id" uuid REFERENCES "app_users"("id") ON DELETE RESTRICT,"internal_notes" varchar(4000),"decision_reason" varchar(2000),"submitted_at" timestamptz(6),"decided_at" timestamptz(6),"created_at" timestamptz(6) NOT NULL DEFAULT now(),"updated_at" timestamptz(6) NOT NULL DEFAULT now());
CREATE INDEX "verification_cases_business_id_status_created_at_idx" ON "verification_cases"("business_id","status","created_at");CREATE INDEX "verification_cases_assigned_to_user_id_status_idx" ON "verification_cases"("assigned_to_user_id","status");
CREATE TABLE "verification_evidence"("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"case_id" uuid NOT NULL REFERENCES "verification_cases"("id") ON DELETE CASCADE,"uploaded_by_user_id" uuid NOT NULL REFERENCES "app_users"("id") ON DELETE RESTRICT,"label" varchar(120) NOT NULL,"object_path" varchar(700) NOT NULL UNIQUE,"mime_type" varchar(120) NOT NULL,"byte_size" integer NOT NULL CHECK("byte_size">0 AND "byte_size"<=10485760),"status" "EvidenceStatus" NOT NULL DEFAULT 'PENDING',"expires_at" timestamptz(6),"created_at" timestamptz(6) NOT NULL DEFAULT now());CREATE INDEX "verification_evidence_case_id_status_idx" ON "verification_evidence"("case_id","status");
CREATE TABLE "evidence_access_logs"("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"evidence_id" uuid NOT NULL REFERENCES "verification_evidence"("id") ON DELETE RESTRICT,"viewer_user_id" uuid NOT NULL REFERENCES "app_users"("id") ON DELETE RESTRICT,"purpose" varchar(200) NOT NULL,"viewed_at" timestamptz(6) NOT NULL DEFAULT now());CREATE INDEX "evidence_access_logs_evidence_id_viewed_at_idx" ON "evidence_access_logs"("evidence_id","viewed_at");CREATE INDEX "evidence_access_logs_viewer_user_id_viewed_at_idx" ON "evidence_access_logs"("viewer_user_id","viewed_at");
CREATE TABLE "verification_badges"("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"business_id" uuid NOT NULL REFERENCES "vendor_businesses"("id") ON DELETE CASCADE,"case_id" uuid NOT NULL UNIQUE REFERENCES "verification_cases"("id") ON DELETE RESTRICT,"scope" "VerificationScope" NOT NULL,"checked_at" timestamptz(6) NOT NULL,"expires_at" timestamptz(6),"disclaimer" varchar(500) NOT NULL,"revoked_at" timestamptz(6),"created_at" timestamptz(6) NOT NULL DEFAULT now());CREATE INDEX "verification_badges_business_id_scope_revoked_at_idx" ON "verification_badges"("business_id","scope","revoked_at");
CREATE TABLE "trust_reports"("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"reporter_user_id" uuid REFERENCES "app_users"("id") ON DELETE SET NULL,"business_id" uuid REFERENCES "vendor_businesses"("id") ON DELETE SET NULL,"type" "TrustReportType" NOT NULL,"subject_type" varchar(60) NOT NULL,"subject_id" uuid,"description" varchar(3000) NOT NULL,"status" "TrustCaseStatus" NOT NULL DEFAULT 'OPEN',"resolution" varchar(2000),"created_at" timestamptz(6) NOT NULL DEFAULT now(),"updated_at" timestamptz(6) NOT NULL DEFAULT now());CREATE INDEX "trust_reports_status_type_created_at_idx" ON "trust_reports"("status","type","created_at");CREATE INDEX "trust_reports_business_id_created_at_idx" ON "trust_reports"("business_id","created_at");
CREATE TABLE "grievances"("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"submitter_user_id" uuid NOT NULL REFERENCES "app_users"("id") ON DELETE RESTRICT,"type" "GrievanceType" NOT NULL,"subject" varchar(160) NOT NULL,"description" varchar(4000) NOT NULL,"status" "TrustCaseStatus" NOT NULL DEFAULT 'OPEN',"assigned_to_user_id" uuid REFERENCES "app_users"("id") ON DELETE RESTRICT,"resolution" varchar(2000),"created_at" timestamptz(6) NOT NULL DEFAULT now(),"updated_at" timestamptz(6) NOT NULL DEFAULT now());CREATE INDEX "grievances_submitter_user_id_created_at_idx" ON "grievances"("submitter_user_id","created_at");CREATE INDEX "grievances_status_created_at_idx" ON "grievances"("status","created_at");
CREATE TABLE "appeals"("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"grievance_id" uuid REFERENCES "grievances"("id") ON DELETE SET NULL,"appellant_user_id" uuid NOT NULL REFERENCES "app_users"("id") ON DELETE RESTRICT,"target_type" varchar(60) NOT NULL,"target_id" uuid NOT NULL,"grounds" varchar(3000) NOT NULL,"status" "AppealStatus" NOT NULL DEFAULT 'OPEN',"decision" varchar(2000),"decided_by_user_id" uuid REFERENCES "app_users"("id") ON DELETE RESTRICT,"created_at" timestamptz(6) NOT NULL DEFAULT now(),"decided_at" timestamptz(6));CREATE INDEX "appeals_appellant_user_id_created_at_idx" ON "appeals"("appellant_user_id","created_at");CREATE INDEX "appeals_status_created_at_idx" ON "appeals"("status","created_at");
CREATE TABLE "trust_audit_logs"("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"actor_user_id" uuid REFERENCES "app_users"("id") ON DELETE SET NULL,"action" varchar(120) NOT NULL,"subject_type" varchar(60) NOT NULL,"subject_id" uuid NOT NULL,"metadata" jsonb NOT NULL DEFAULT '{}',"created_at" timestamptz(6) NOT NULL DEFAULT now());CREATE INDEX "trust_audit_logs_subject_type_subject_id_created_at_idx" ON "trust_audit_logs"("subject_type","subject_id","created_at");CREATE INDEX "trust_audit_logs_actor_user_id_created_at_idx" ON "trust_audit_logs"("actor_user_id","created_at");

INSERT INTO "permissions"("code","description") VALUES ('verification.review','Review assigned verification cases'),('trust.moderate','Moderate reports and grievances'),('appeal.decide','Decide trust appeals'),('audit.read','Read trust audit logs') ON CONFLICT("code") DO NOTHING;
INSERT INTO "role_permissions"("role_id","permission_id") SELECT r.id,p.id FROM "roles" r CROSS JOIN "permissions" p WHERE (r.code='VERIFIER' AND p.code='verification.review') OR (r.code IN('MODERATOR','SUPER_ADMIN') AND p.code IN('trust.moderate','appeal.decide','audit.read')) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types) VALUES('verification-evidence','verification-evidence',false,10485760,ARRAY['application/pdf','image/jpeg','image/png']) ON CONFLICT(id) DO UPDATE SET public=false,file_size_limit=10485760;

ALTER TABLE "verification_cases" ENABLE ROW LEVEL SECURITY;ALTER TABLE "verification_evidence" ENABLE ROW LEVEL SECURITY;ALTER TABLE "evidence_access_logs" ENABLE ROW LEVEL SECURITY;ALTER TABLE "verification_badges" ENABLE ROW LEVEL SECURITY;ALTER TABLE "trust_reports" ENABLE ROW LEVEL SECURITY;ALTER TABLE "grievances" ENABLE ROW LEVEL SECURITY;ALTER TABLE "appeals" ENABLE ROW LEVEL SECURITY;ALTER TABLE "trust_audit_logs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "verification_cases","verification_evidence","evidence_access_logs","verification_badges","trust_reports","grievances","appeals","trust_audit_logs" FROM anon,authenticated;
CREATE OR REPLACE FUNCTION prevent_trust_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'Trust audit records are immutable';END$$;CREATE TRIGGER trust_audit_immutable BEFORE UPDATE OR DELETE ON "trust_audit_logs" FOR EACH ROW EXECUTE FUNCTION prevent_trust_audit_mutation();CREATE TRIGGER evidence_access_immutable BEFORE UPDATE OR DELETE ON "evidence_access_logs" FOR EACH ROW EXECUTE FUNCTION prevent_trust_audit_mutation();
