import { BadRequestException, ConflictException, ForbiddenException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import type { Prisma, VendorStatus } from '@prisma/client';
import { PrismaService } from '../platform/prisma.service';
import { businessInput, businessPatch, categoriesInput, decisionInput, packageInput, serviceAreasInput, serviceInput, termsInput } from './vendor.schemas';

const editable: VendorStatus[] = ['DRAFT','CHANGES_REQUESTED','REJECTED'];
@Injectable()
export class VendorsService {
  constructor(@Inject(PrismaService) private readonly db: PrismaService) {}
  async create(userId: string, body: unknown) {
    const data = businessInput.parse(body); await this.validateCity(data.baseCityId);
    return this.db.$transaction(async tx => { const business = await tx.vendorBusiness.create({ data: data as unknown as Prisma.VendorBusinessUncheckedCreateInput }); await tx.vendorMember.create({ data: { businessId: business.id, userId, role: 'OWNER' } }); await tx.vendorCreditAccount.create({data:{businessId:business.id}}); return business; });
  }
  async dashboard(userId: string, id: string) { await this.assertMember(userId,id); await this.refreshProgress(id); return this.full(id); }
  async update(userId: string, id: string, body: unknown) { await this.assertEditable(userId,id); const data=businessPatch.parse(body); await this.validateCity(data.baseCityId); await this.db.vendorBusiness.update({ where:{id}, data:data as Prisma.VendorBusinessUncheckedUpdateInput }); await this.refreshProgress(id); return this.full(id); }
  async setCategories(userId:string,id:string,body:unknown) { await this.assertEditable(userId,id); const data=categoriesInput.parse(body); const ids=[data.primaryCategoryId,...new Set(data.secondaryCategoryIds)]; if(await this.db.category.count({where:{id:{in:ids},active:true}})!==ids.length) throw new BadRequestException('One or more categories are invalid'); await this.db.$transaction([this.db.vendorCategory.deleteMany({where:{businessId:id}}),...ids.map(categoryId=>this.db.vendorCategory.create({data:{businessId:id,categoryId,isPrimary:categoryId===data.primaryCategoryId}}))]); await this.refreshProgress(id); return this.full(id); }
  async setAreas(userId:string,id:string,body:unknown) { await this.assertEditable(userId,id); const {locationIds}=serviceAreasInput.parse(body); const unique=[...new Set(locationIds)]; if(await this.db.location.count({where:{id:{in:unique},active:true,type:{in:['CITY','LOCALITY']}}})!==unique.length) throw new BadRequestException('Service areas must be active cities or localities'); await this.db.$transaction([this.db.vendorServiceArea.deleteMany({where:{businessId:id}}),...unique.map(locationId=>this.db.vendorServiceArea.create({data:{businessId:id,locationId}}))]); await this.refreshProgress(id); return this.full(id); }
  async addService(userId:string,id:string,body:unknown) { await this.assertEditable(userId,id); const data=serviceInput.parse(body); if(!await this.db.vendorCategory.findUnique({where:{businessId_categoryId:{businessId:id,categoryId:data.categoryId}}})) throw new BadRequestException('Service category must be selected for this business'); const row=await this.db.vendorService.create({data:{...data,businessId:id} as unknown as Prisma.VendorServiceUncheckedCreateInput}); await this.refreshProgress(id); return row; }
  async addPackage(userId:string,id:string,body:unknown) { await this.assertEditable(userId,id); const data=packageInput.parse(body); if(data.serviceId && !await this.db.vendorService.findFirst({where:{id:data.serviceId,businessId:id}})) throw new BadRequestException('Service does not belong to this business'); const row=await this.db.vendorPackage.create({data:{...data,businessId:id} as unknown as Prisma.VendorPackageUncheckedCreateInput}); await this.refreshProgress(id); return row; }
  async acceptTerms(userId:string,id:string,body:unknown) { await this.assertEditable(userId,id); const data=termsInput.parse(body); const row=await this.db.vendorTermsAcceptance.upsert({where:{businessId_version:{businessId:id,version:data.version}},create:{...data,businessId:id,userId},update:{termsHash:data.termsHash,userId,acceptedAt:new Date()}}); await this.refreshProgress(id); return row; }
  async preview(userId:string,id:string) { await this.assertMember(userId,id); return this.full(id); }
  async submit(userId:string,id:string) { const b=await this.assertEditable(userId,id); const missing=await this.missing(id,b); if(missing.length) throw new BadRequestException({message:'Onboarding is incomplete',missing}); return this.db.$transaction(async tx=>{const current=await tx.vendorBusiness.update({where:{id},data:{status:'SUBMITTED',submittedAt:new Date(),completionPercent:100,onboardingStep:14}}); await tx.vendorModerationEvent.create({data:{businessId:id,actorUserId:userId,fromStatus:b.status,toStatus:'SUBMITTED'}}); return current;}); }
  async moderate(actorUserId:string,id:string,body:unknown) { const data=decisionInput.parse(body); const b=await this.db.vendorBusiness.findUnique({where:{id}}); if(!b) throw new NotFoundException('Business not found'); if(b.status!=='SUBMITTED') throw new ConflictException('Only submitted businesses can be moderated'); return this.db.$transaction(async tx=>{const approved=data.decision==='APPROVED',updated=await tx.vendorBusiness.update({where:{id},data:{status:data.decision,approvedAt:approved?new Date():null,publicVisible:approved}});if(approved)await tx.vendorDiscoveryProfile.upsert({where:{businessId:id},create:{businessId:id},update:{lastActiveAt:new Date()}});await tx.vendorModerationEvent.create({data:{businessId:id,actorUserId,fromStatus:b.status,toStatus:data.decision,reason:data.reason ?? null}}); return updated;}); }
  listSubmissions() { return this.db.vendorBusiness.findMany({where:{status:'SUBMITTED'},orderBy:{submittedAt:'asc'},include:{baseCity:true,categories:{where:{isPrimary:true},include:{category:true}}}}); }
  private full(id:string) { return this.db.vendorBusiness.findUnique({where:{id},include:{baseCity:true,categories:{include:{category:true}},serviceAreas:{include:{location:true}},services:true,packages:true,terms:{orderBy:{acceptedAt:'desc'}},moderationEvents:{orderBy:{createdAt:'desc'}}}}); }
  private async assertMember(userId:string,id:string) { if(!await this.db.vendorMember.findFirst({where:{businessId:id,userId,active:true}})) throw new ForbiddenException('Business access denied'); }
  private async assertEditable(userId:string,id:string) { await this.assertMember(userId,id); const b=await this.db.vendorBusiness.findUnique({where:{id}}); if(!b) throw new NotFoundException('Business not found'); if(!editable.includes(b.status)) throw new ConflictException('Business onboarding is not editable'); return b; }
  private async validateCity(id?:string|null) { if(id && !await this.db.location.findFirst({where:{id,type:'CITY',active:true}})) throw new BadRequestException('Base city must be an active city'); }
  private async missing(id:string,b:{description:string|null;baseCityId:string|null}) { const [primary,areas,services,terms]=await Promise.all([this.db.vendorCategory.count({where:{businessId:id,isPrimary:true}}),this.db.vendorServiceArea.count({where:{businessId:id}}),this.db.vendorService.count({where:{businessId:id,active:true}}),this.db.vendorTermsAcceptance.count({where:{businessId:id}})]); return [...(!b.description?['description']:[]),...(!b.baseCityId?['baseCity']:[]),...(!primary?['primaryCategory']:[]),...(!areas?['serviceAreas']:[]),...(!services?['services']:[]),...(!terms?['termsAcceptance']:[])]; }
  private async refreshProgress(id:string) { const b=await this.db.vendorBusiness.findUniqueOrThrow({where:{id}}); const missing=await this.missing(id,b); const complete=6-missing.length; await this.db.vendorBusiness.update({where:{id},data:{completionPercent:Math.round(complete/6*100),onboardingStep:Math.min(13,Math.max(2,complete+3))}}); }
}
