import { z } from 'zod';
export const businessInput = z.object({ name: z.string().min(2).max(160), slug: z.string().min(2).max(180).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), professionalType: z.enum(['FREELANCER','SOLE_PROPRIETOR','STUDIO','AGENCY','REGISTERED_COMPANY','VENUE_PROPERTY','PERFORMER','BOUTIQUE_RENTAL']), description: z.string().max(5000).nullable().optional(), yearsExperience: z.number().int().min(0).max(100).nullable().optional(), languages: z.array(z.string().min(2).max(50)).max(20).default([]), baseCityId: z.string().uuid().nullable().optional(), outstationAvailable: z.boolean().default(false) });
export const businessPatch = businessInput.omit({ slug: true }).partial();
export const categoriesInput = z.object({ primaryCategoryId: z.string().uuid(), secondaryCategoryIds: z.array(z.string().uuid()).max(10).default([]) }).refine(v => !v.secondaryCategoryIds.includes(v.primaryCategoryId), 'Primary category cannot also be secondary');
export const serviceAreasInput = z.object({ locationIds: z.array(z.string().uuid()).min(1).max(100) });
export const serviceInput = z.object({ categoryId: z.string().uuid(), name: z.string().min(2).max(140), description: z.string().max(1000).nullable().optional(), pricingType: z.enum(['FIXED','STARTING_FROM','CUSTOM_QUOTE']), price: z.number().nonnegative().nullable().optional(), active: z.boolean().default(true), sortOrder: z.number().int().default(0) }).superRefine((v,c) => { if (v.pricingType === 'CUSTOM_QUOTE' ? v.price != null : v.price == null) c.addIssue({ code:'custom', message:'Price is required except for custom quotes' }); });
export const packageInput = z.object({ serviceId: z.string().uuid().nullable().optional(), name: z.string().min(2).max(140), description: z.string().max(1200).nullable().optional(), price: z.number().nonnegative(), inclusions: z.array(z.string().min(1).max(200)).max(50).default([]), active: z.boolean().default(true) });
export const termsInput = z.object({ version: z.string().min(1).max(40), termsHash: z.string().length(64).regex(/^[a-f0-9]{64}$/) });
export const decisionInput = z.object({ decision: z.enum(['APPROVED','REJECTED','CHANGES_REQUESTED']), reason: z.string().max(1000).nullable().optional() }).superRefine((v,c) => { if (v.decision !== 'APPROVED' && !v.reason) c.addIssue({ code:'custom', message:'A reason is required' }); });
