import { BadRequestException, ConflictException, ForbiddenException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import type { Prisma } from '@prisma/client';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { randomUUID } from 'node:crypto';
import { PrismaService } from '../platform/prisma.service';
import { copyrightInput,mediaDecisionInput,postInput,uploadIntentInput } from './media.schemas';
const BUCKET='portfolio-private';
@Injectable()
export class MediaService {
 private readonly storage:SupabaseClient;
 constructor(@Inject(PrismaService) private readonly db:PrismaService){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY;if(!url||!key)throw new Error('Supabase Storage server credentials are required');this.storage=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
 async signedUpload(userId:string,businessId:string,body:unknown){await this.member(userId,businessId);const d=uploadIntentInput.parse(body),ext=d.filename.split('.').pop()?.toLowerCase()??'bin',path=`${businessId}/${new Date().toISOString().slice(0,10)}/${randomUUID()}.${ext}`,expiresAt=new Date(Date.now()+10*60_000);const intent=await this.db.mediaUploadIntent.create({data:{businessId,userId,objectPath:path,mediaType:d.mediaType,mimeType:d.mimeType,expectedSize:d.byteSize,expiresAt}});const {data,error}=await this.storage.storage.from(BUCKET).createSignedUploadUrl(path);if(error){await this.db.mediaUploadIntent.delete({where:{id:intent.id}});throw new BadRequestException(`Storage upload could not be signed: ${error.message}`);}return {intentId:intent.id,path,signedUrl:data.signedUrl,token:data.token,expiresAt};}
 async complete(userId:string,businessId:string,intentId:string){await this.member(userId,businessId);const i=await this.db.mediaUploadIntent.findFirst({where:{id:intentId,businessId}});if(!i)throw new NotFoundException('Upload intent not found');if(i.consumedAt)throw new ConflictException('Upload intent already consumed');if(i.expiresAt<new Date())throw new ConflictException('Upload intent expired');const parts=i.objectPath.split('/'),file=parts.pop()!,folder=parts.join('/');const {data,error}=await this.storage.storage.from(BUCKET).list(folder,{search:file,limit:2});if(error||!data?.some(x=>x.name===file))throw new BadRequestException('Uploaded object was not found');const asset=await this.db.$transaction(async tx=>{await tx.mediaUploadIntent.update({where:{id:i.id},data:{consumedAt:new Date()}});const a=await tx.mediaAsset.create({data:{businessId,objectPath:i.objectPath,mediaType:i.mediaType,mimeType:i.mimeType,byteSize:i.expectedSize,rightsDeclared:true,processingStatus:'QUEUED'}});await tx.$queryRaw`SELECT pgmq.send('media_processing', ${JSON.stringify({mediaId:a.id})}::jsonb)`;return a;});return asset;}
 async createPost(userId:string,businessId:string,body:unknown){await this.member(userId,businessId);const d=postInput.parse(body),ids=[...new Set(d.mediaIds)];if(ids.length!==d.mediaIds.length)throw new BadRequestException('Duplicate media is not allowed');const media=await this.db.mediaAsset.findMany({where:{id:{in:ids},businessId}});if(media.length!==ids.length)throw new BadRequestException('Media does not belong to this business');if((d.format==='SINGLE_IMAGE'&&ids.length!==1)||(d.format==='ALBUM'&&ids.length<2))throw new BadRequestException('Media count does not match portfolio format');return this.db.$transaction(async tx=>{const post=await tx.portfolioPost.create({data:{businessId,categoryId:d.categoryId,cityId:d.cityId,relatedPackageId:d.relatedPackageId??null,format:d.format,caption:d.caption??null,eventType:d.eventType??null,tags:d.tags} as Prisma.PortfolioPostUncheckedCreateInput});await Promise.all(ids.map((mediaId,sortOrder)=>tx.portfolioMedia.create({data:{postId:post.id,mediaId,sortOrder,isCover:mediaId===d.coverMediaId}})));return post;});}
 async publish(userId:string,businessId:string,postId:string){await this.member(userId,businessId);const post=await this.db.portfolioPost.findFirst({where:{id:postId,businessId},include:{media:{include:{media:true}}}});if(!post)throw new NotFoundException('Portfolio post not found');if(post.media.some(x=>x.media.processingStatus!=='READY'||x.media.moderationStatus!=='APPROVED'))throw new ConflictException('All media must be processed and approved');return this.db.portfolioPost.update({where:{id:postId},data:{publicationStatus:'PUBLISHED',publishedAt:new Date()}});}
 async archive(userId:string,businessId:string,postId:string){await this.member(userId,businessId);return this.db.portfolioPost.updateMany({where:{id:postId,businessId},data:{publicationStatus:'ARCHIVED'}});}
 async retry(userId:string,businessId:string,mediaId:string){await this.member(userId,businessId);const a=await this.db.mediaAsset.findFirst({where:{id:mediaId,businessId}});if(!a)throw new NotFoundException('Media not found');if(a.processingStatus!=='FAILED')throw new ConflictException('Only failed media can be retried');return this.db.$transaction(async tx=>{const x=await tx.mediaAsset.update({where:{id:mediaId},data:{processingStatus:'QUEUED',failureReason:null,retryCount:{increment:1}}});await tx.$queryRaw`SELECT pgmq.send('media_processing', ${JSON.stringify({mediaId})}::jsonb)`;return x;});}
 moderationQueue(){return this.db.mediaAsset.findMany({where:{processingStatus:'READY',moderationStatus:'PENDING'},orderBy:{createdAt:'asc'},include:{business:{select:{id:true,name:true}}}});}
 async moderate(actorUserId:string,mediaId:string,body:unknown){const d=mediaDecisionInput.parse(body),a=await this.db.mediaAsset.findUnique({where:{id:mediaId}});if(!a)throw new NotFoundException('Media not found');if(a.processingStatus!=='READY')throw new ConflictException('Media processing is incomplete');return this.db.$transaction(async tx=>{const x=await tx.mediaAsset.update({where:{id:mediaId},data:{moderationStatus:d.decision}});await tx.mediaModerationEvent.create({data:{mediaId,actorUserId,decision:d.decision,reason:d.reason??null}});return x;});}
 async publicPortfolio(vendorSlug:string){const posts=await this.db.portfolioPost.findMany({where:{business:{slug:vendorSlug,status:'APPROVED'},publicationStatus:'PUBLISHED',media:{every:{media:{processingStatus:'READY',moderationStatus:'APPROVED'}}}},orderBy:{publishedAt:'desc'},include:{business:{select:{name:true,slug:true}},category:true,city:true,media:{orderBy:{sortOrder:'asc'},include:{media:true}}}});return Promise.all(posts.map(async p=>({...p,media:await Promise.all(p.media.map(async m=>{const path=m.media.processedPath??m.media.objectPath,{data}=await this.storage.storage.from(BUCKET).createSignedUrl(path,3600);return {...m,url:data?.signedUrl??null};}))})));}
 reportCopyright(body:unknown){const d=copyrightInput.parse(body);return this.db.copyrightReport.create({data:d});}
 private async member(userId:string,businessId:string){if(!await this.db.vendorMember.findFirst({where:{userId,businessId,active:true}}))throw new ForbiddenException('Business access denied');}
}
